//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_SERVER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Size { get; set; }
        public double Price { get; set; }
        public Nullable<System.DateTime> Constraction_s_Date { get; set; }
        public string Note { get; set; }
        public Nullable<double> Sold { get; set; }
        public string OwnerName { get; set; }
        public string OwnerPhone { get; set; }
    }
}
